Resturant/Models/FoodItem.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;
using System.Xml.Linq;

namespace Resturant.Models
{
    public class FoodItem
    {
        [Key]
        public int FoodItemId { get; set; }

        [Required]
        public string Name { get; set; }

        [DataType(DataType.Currency, ErrorMessage = "You did not enter a valid currency value ex. $15.6")]
        public decimal Price { get; set; }

        [Required]
        public int Quantity { get; set; }

        [Required]
        public string Category { get; set; }

        [Display(Name = "Image")]
        [DefaultValue("default.jpg")]
        public string Foodpic { get; set; }

        public ICollection<Order>? Orders { get; set; }
    }
}

Resturant/Controllers/FoodItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting;
using Resturant.Data;
using Resturant.Models;

namespace Resturant.Controllers
{
    public class FoodItemsController : Controller
    {
        private readonly ApplicationDbContext db;
        private readonly IWebHostEnvironment _environment;
        public FoodItemsController(ApplicationDbContext db, IWebHostEnvironment environment)
        {
            this.db = db;
            _environment = environment;

        }

        // GET: FoodItems
        public async Task<IActionResult> Index()
        {
            IEnumerable<FoodItem> items = db.FoodItems.ToList();
            return View(items);
            //return db.FoodItems != null ? 
            //            View(await db.FoodItems.ToListAsync()) :
            //            Problem("Entity set 'ApplicationDbContext.FoodItems'  is null.");
        }

        public async Task<IActionResult> Menu()
        {
            return View(await db.FoodItems.ToListAsync());
        }



        // GET: FoodItems/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || db.FoodItems == null)
            {
                return NotFound();
            }

            var foodItem = await db.FoodItems
                .FirstOrDefaultAsync(m => m.FoodItemId == id);
            if (foodItem == null)
            {
                return NotFound();
            }

            return View(foodItem);
        }

        // GET: FoodItems/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: FoodItems/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]  // to more security
        public async Task<IActionResult> Create([Bind("FoodItemId,Name,Price,Quantity,Category,Foodpic")] FoodItem Item, IFormFile img_file)
        {
            // to create Images folder in the project Path.
            string path = Path.Combine(_environment.WebRootPath, "images"); // wwwroot/Img/
            if (!Directory.Exists(path))
            {
                Directory.CreateDirectory(path);
            }
            if (img_file != null)
            {
                path = Path.Combine(path, img_file.FileName); // for exmple : /Img/Photoname.png
                using (var stream = new FileStream(path, FileMode.Create))
                {
                    await img_file.CopyToAsync(stream);
                    ViewBag.Message = string.Format("<b>{0}</b> uploaded.</br>", img_file.FileName.ToString());
                    Item.Foodpic = img_file.FileName;
                }
            }
            else
            {
                Item.Foodpic = "default.jpg";//to save the default image path in database;
            }
            try
            {
                db.Add(Item);
                db.SaveChanges();
                return RedirectToAction("Index");


            }
            catch (Exception ex) { ViewBag.exc = ex.Message; }
            return View();
        }


        // GET: FoodItems/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || db.FoodItems == null)
            {
                return NotFound();
            }

            var foodItem = await db.FoodItems.FindAsync(id);
            if (foodItem == null)
            {
                return NotFound();
            }
            return View(foodItem);
        }

        // POST: FoodItems/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("FoodItemId,Name,Price,Quantity,Category,Foodpic")] FoodItem foodItem)
        {
            if (id != foodItem.FoodItemId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    db.Update(foodItem);
                    await db.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FoodItemExists(foodItem.FoodItemId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(foodItem);
        }

        // GET: FoodItems/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || db.FoodItems == null)
            {
                return NotFound();
            }

            var foodItem = await db.FoodItems
                .FirstOrDefaultAsync(m => m.FoodItemId == id);
            if (foodItem == null)
            {
                return NotFound();
            }

            return View(foodItem);
        }

        // POST: FoodItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (db.FoodItems == null)
            {
                return Problem("Entity set 'ApplicationDbContext.FoodItems'  is null.");
            }
            var foodItem = await db.FoodItems.FindAsync(id);
            if (foodItem != null)
            {
                db.FoodItems.Remove(foodItem);
            }
            
            await db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FoodItemExists(int id)
        {
          return (db.FoodItems?.Any(e => e.FoodItemId == id)).GetValueOrDefault();
        }
    }
}

Resturant/Controllers/OrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Resturant.Data;
using Resturant.Models;
using static NuGet.Packaging.PackagingConstants;

namespace Resturant.Controllers
{
    public class OrdersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public OrdersController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Orders
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Orders.Include(o => o.FoodItem).Include(o => o.User);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Orders/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Orders == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .Include(o => o.FoodItem)
                .Include(o => o.User)
                .FirstOrDefaultAsync(m => m.OrderId == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // GET: Orders/Create
        public async Task<IActionResult> Create(int? id)
        {
            
            var Items = await _context.FoodItems.FindAsync(id);
            return View(Items);
        }


        // POST: Orders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int fooditemId, int quantity)
        {
            // Get the user ID from the session
            int userid = Convert.ToInt32(HttpContext.Session.GetString("userid"));

            // Check if the user exists in the database
            User user = await _context.Users.FindAsync(userid);
            if (user == null)
            {
                // Return an error message if the user does not exist
                ModelState.AddModelError("", "User not found");
                return View();
            }

            // Create a new order object and set its properties
            Order order = new Order
            {
                fooditemId = fooditemId,
                quantity = quantity,
                userid = userid,
                orderdate = DateTime.Today
            };

            // Add the new order to the database and save changes
            _context.Orders.Add(order);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Cart));
        }
        public async Task<IActionResult> Cart()// for customer
        {
            ViewData["FoodItems"] = _context.FoodItems.ToList();
            int id = Convert.ToInt32(HttpContext.Session.GetString("userid")); ;
            var items = await _context.Orders.FromSqlRaw("select * from Orders where userid = '" + id + "' ").ToListAsync();
            return View(items);
        }
       

        public async Task<IActionResult> customerOrders(int? id)// for Admin
        {


            var Items = await _context.Orders.FromSqlRaw("select *  from Orders where  userid = '" + id + "'  ").ToListAsync();
            return View(Items);

        }

        // GET: Orders/Edit/5
        public async Task<IActionResult> Edit(int? id)
            {
            if (id == null || _context.Orders == null)
            {
                return NotFound();
            }

            var order = await _context.Orders.FindAsync(id);
            if (order == null)
            {
                return NotFound();
            }
            ViewData["fooditemId"] = new SelectList(_context.FoodItems, "FoodItemId", "Category", order.fooditemId);
            ViewData["userid"] = new SelectList(_context.Users, "UserId", "Email", order.userid);
            return View(order);
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("OrderId,fooditemId,userid,quantity,orderdate")] Order order)
        {
            if (id != order.OrderId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(order);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrderExists(order.OrderId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Cart));
            }
            ViewData["fooditemId"] = new SelectList(_context.FoodItems, "FoodItemId", "Category", order.fooditemId);
            ViewData["userid"] = new SelectList(_context.Users, "UserId", "Email", order.userid);
            return View(order);
        }

        // GET: Orders/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Orders == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .Include(o => o.FoodItem)
                .Include(o => o.User)
                .FirstOrDefaultAsync(m => m.OrderId == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Orders == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Orders'  is null.");
            }
            var order = await _context.Orders.FindAsync(id);
            if (order != null)
            {
                _context.Orders.Remove(order);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Cart));
        }

        private bool OrderExists(int id)
        {
          return (_context.Orders?.Any(e => e.OrderId == id)).GetValueOrDefault();
        }
    }
}

Resturant/Views/FoodItems/Create.cshtml
@model Resturant.Models.FoodItem

@{
    ViewData["Title"] = "Create";
}
<style>
    body {
        background-image: url("/images/background2.jpg");
        background-size: cover;
        background-repeat: no-repeat;
    }
</style>

<h4>Add New FoodItem</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Category" class="control-label"></label>
                <select name="Category" class="form-control" asp-for="Category">
                    <option value="0">Please select</option>
                    <option value="Pizza">Pizza</option>
                    <option value="Burger">Burger</option>
                    <option value="Chicken">Chicken</option>
                    <option value="Snacks">Snacks</option>
                </select>
                <span asp-validation-for="Category" class="text-danger"></span>
            </div>
            <div class="form-group">
            <label asp-for="Foodpic" class="control-label"></label>
            <input asp-for="Foodpic" class="form-control" type="file" name="img_file" />
            <span asp-validation-for="Foodpic" class="text-danger"></span>
             </div>

    <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>

        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Resturant/Views/FoodItems/Delete.cshtml
@model Resturant.Models.FoodItem

@{
    ViewData["Title"] = "Delete";
}

<style>
    body {
        background-image: url("/images/background2.jpg");
        background-size: cover;
        background-repeat: no-repeat;
    }
</style>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>FoodItem</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category)
        </dd>
        
        <td>
            <img src="~/images/@Model.Foodpic" alt=" food_pic here" style="border-radius:50%; width:70px;height :70px">

        </td>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="FoodItemId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Resturant/Views/FoodItems/Details.cshtml
@model Resturant.Models.FoodItem

@{
    ViewData["Title"] = "Details";
}

<style>
    body {
        background-image: url("/images/background2.jpg");
        background-size: cover;
        background-repeat: no-repeat;
    }
</style>

<div>
    <h4>FoodItem</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Category)
        </dd>
        <dt class = "col-sm-2">
           
        </dt>
        <td>
            <img src="~/images/@Model.Foodpic" alt=" food_pic here" style="border-radius:50%; width:70px;height :70px">

        </td>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.FoodItemId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Resturant/Views/FoodItems/Edit.cshtml
@model Resturant.Models.FoodItem

@{
    ViewData["Title"] = "Edit";
}

<style>
    body {
        background-image: url("/images/background2.jpg");
        background-size: cover;
        background-repeat: no-repeat;
    }
</style>

<h4>FoodItem</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="FoodItemId" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Category" class="control-label"></label>
                <select name="Category" class="form-control" asp-for="Category">
                    <option value="0">Please select</option>
                    <option value="Pizza">Pizza</option>
                    <option value="Burger">Burger</option>
                    <option value="Chicken">Chicken</option>
                    <option value="Snacks">Snacks</option>
                </select>
                <span asp-validation-for="Category" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Foodpic" class="control-label"></label>
                <input asp-for="Foodpic" class="form-control" type="file" name="img_file" />
                <span asp-validation-for="Foodpic" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Resturant/Views/FoodItems/Index.cshtml
@model IEnumerable<Resturant.Models.FoodItem>

@{
    ViewData["Title"] = "Index";
}

<style>
     body {
         background-image: url("/images/background1.jpg");
         background-size: cover;
         background-repeat: no-repeat;
     }
</style>

<table class="table" style=" color: #FFFFFF;border: none;">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Foodpic)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Category)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quantity)
            </th>
           
            
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
                <td>
                    <img src="~/images/@item.Foodpic" alt=" food_pic here" style="border-radius:50%; width:70px;height :70px">

                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Category)
                </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Quantity)
            </td>
            
            
            <td>
                <a asp-action="Edit" asp-route-id="@item.FoodItemId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.FoodItemId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.FoodItemId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
<a asp-controller="FoodItems" asp-action="Create" class="btn btn-primary">Add New Food Item</a>

Resturant/Views/FoodItems/Menu.cshtml
@model IEnumerable<Resturant.Models.FoodItem>

@{
    ViewData["Title"] = "Menu";
}
@{
    Layout = "~/Views/Shared/_Layout1.cshtml";
}
<style>
    body {
        background-image: url("/images/background1.jpg");
        background-size: cover;
        background-repeat: no-repeat;
    }
</style>
<table class="table" style=" color: #FFFFFF;border: none;">
    <thead>
        <tr>
            <th>Name </th>
            <th>image</th>
            <th>Price</th>

            <th style="border:none"></th>

        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Name</td>

                <td>
                    <img src="~/images/@item.Foodpic" alt=" food_pic here" style="border-radius:50%; width:70px;height :70px">

                </td>
                <td>@item.Price</td>
                <td style="border:none">
                    <a asp-action="Create" asp-controller="Orders" asp-route-id="@item.FoodItemId" class="btn btn-primary"
                       style=" margin-top: 0px; margin-left:30px;">AddToCart </a>
                </td>

            </tr>
        }
    </tbody>
</table>